configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/prelude%2Fprelude-47eec00cf307d15f01f8efefdbd484fd778ed0ee1abeadf8cac2fa1a3f41d8f7.yml
openapi_spec_hash: 4d00170e690576a78af320a62cfeb9ff
config_hash: 3f1b822206b070cb6a326cbd911b856c
